### ISSUE TITLE
Problema a la hora de coger los puntos del pod y mostrarlos en el mapa

### ISSUE THREAD

**Issue by aaronof17** [Arquisoft/lomap_es4b#16]
Estoy teniendo ciertos problemas a la hora de leer del pod el json y luego convertir los datos en objetos Puntos. Y luego enviarlos al mapa para poder mostrarlos

**Comment by uo276467** [comment]
Los puntos se están recogiendo correctamente, pero se muestran al pulsar en la opción "Marcadores". Buscar la forma de que se muestren la primera vez que se carga el mapa en pantalla.

**Comment by UO276723** [comment]
SOLUCION: cargar los puntos en el evento "whenReady" del mapa, y crear y asociar los marcadores a este una vez que los puntos se obtengan del POD.
